# Deploys the API to testnet when a PR is opened, reopened or edited regardless
# of from where it branched from, as long as a change has occurred in the api
# folder
name: API Testnet
on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      - 'packages/api/**'
jobs:
  deploy_api_testnet:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          workload_identity_provider: 'projects/803405501117/locations/global/workloadIdentityPools/automation-pool/providers/automation-provider'
          service_account: 'automation@dopewars-live.iam.gserviceaccount.com'

      - id: 'deploy-api'
        uses: 'google-github-actions/deploy-appengine@v0.8.0'
        with:
          deliverables: 'app.testnet.api.yaml'

      - id: 'deploy-indexer'
        uses: 'google-github-actions/deploy-appengine@v0.8.0'
        with:
          deliverables: 'app.testnet.indexer.yaml'
