# name: Tests

# on: [push, pull_request]
# on: []

# jobs:
#   tests:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#       - uses: cachix/install-nix-action@v13
#       - uses: cachix/cachix-action@v10
#         with:
#           name: dapp

#       - name: Install dependencies
#         run: cd packages/contracts && nix-shell --run 'make'

#       - name: Run tests
#         run: cd packages/contracts && nix-shell --run 'make test'
#         env:
#          ETH_RPC_URL: https://eth-mainnet.alchemyapi.io/v2/${{ secrets.ALCHEMY_API_KEY }}

name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_S3_ID: ${{ secrets.S3_ID }}
          envkey_S3_SECRET: ${{ secrets.S3_SECRET }}
          envkey_SECRET_WORD: ${{ secrets.SECRET_WORD }}
      - name: Set up Javascript
        run: yarn
      - name: Test Web
        run: yarn web test --passWithNoTests
      - name: Build Web
        run: yarn web build
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.15
      - name: Test Go
        run: go test -v ./...
        working-directory: packages/api
      - name: Build Go
        run: go build -v ./...
        working-directory: packages/api

